= Manuel de l'ECDIS des eaux intérieures
:icons: font

== Introduction

Ce manuel décrit l'utilisation d'OpenCPN comme requis par les règles de Inland ECDIS Édition 2.4 (Mode d'information).

link:https://unece.org/fileadmin/DAM/trans/doc/2015/sc3wp3/Presentation_WP3_-_Inland_ECDIS_edition_2.4.pdf[Inland ECDIS Edition 2.4 Mandate]

link:https://unece.org/fileadmin/DAM/trans/doc/2016/sc3wp3/ECE-TRANS-SC3-156-Rev3e.pdf[Inland ECDIS Edition 2.4 Technical Specifications]

Une introduction à l'ECDIS des eaux intérieures peut être trouvée https://www.ccr-zkr.org/files/documents/workshops/wrshp181011/Leaflet_Inland_ECDIS_fr.pdf[Ici].

Une page de liens utiles, y compris les organisations nationales qui s'occupent des IENC se trouve sur https://ienc.openecdis.org/links[Ici].

Le manuel est basé sur la version 5.6.2 d'OpenCPN. Il n'inclut pas d'informations sur la version Android du programme.

[NOTE]
====
L'ECDIS intérieur est une norme définie (2.4 est la norme actuelle) obligatoire pour les navires commerciaux sur les eaux intérieures de l'UE.
Les cartes S-57 correspondantes sont appelées InlandENC et ont certains paramètres spécifiques.

L'ECDIS intérieur ne doit pas être confondu avec l'IMO ECDIS. Les deux sont des systèmes complètement différents.

La police de l'eau ou d'autres autorités vérifie les navires et les barges pour le respect des règles de l'ECDIS intérieur.
Il est important que OpenCPN apparaisse dans la liste des logiciels approuvés.

La norme ECDIS intérieure impose le démarrage en mode nuit. OpenCPN doit avoir des échelles prédéfinies à partir des gammes radars standard.
Il y a aussi des modes d'affichage basiques des jeux de cartes.

La norme ECDIS intérieure distingue deux modes de fonctionnement : le mode de navigation et le mode d'information.
OpenCPN est conforme au mode d'information.

Inland ECDIS 2.4 requiert un manuel dans les langues EN, FR, NL, DE au minimum.
====

== État de correction du manuel

L'annexe contient une liste source montrant les dernières modifications apportées aux pages du manuel.

== Annexe

link:https://opencpn-manuals.github.io/inland-ecdis/manuals/en/sources.html[Les dernières modifications]
