= Inland ECDIS handleiding
:icons: font

== Introductie

Deze handleiding beschrijft het gebruik van OpenCPN zoals dat vereist is door de regels van Inland ECDIS uitgave 2.4 (Informatiemodus).

link:https://unece.org/fileadmin/DAM/trans/doc/2015/sc3wp3/Presentation_WP3_-_Inland_ECDIS_edition_2.4.pdf[Inland_ECDIS_edition_2.4]

Een inleiding tot Inland ECDIS kan worden gevonden op https://www.ccr-zkr.org/files/documents/workshops/wrshp181011/Leaflet_Inland_ECDIS_nl.pdf[HIER].

Een pagina met nuttige links, inclusief nationale organisaties die zich bezighouden met IENC's wordt gevonden https://ienc.openecdis.org/links[HIER].

De handleiding is gebaseerd op versie 5.6.2 van OpenCPN. Het bevat geen informatie over de Android-versie van het programma.

[NOTE]

====
Inland ECDIS is een gedefinieerde norm (2,4 is de huidige) die verplicht is voor commerciële vaartuigen in de EU-Inland wateren.
De bijbehorende S-57 kaarten worden InlandENC's genoemd en hebben enkele specifieke parameters.

Inland ECDIS mag niet worden verward met IMO ECDIS.
Het gaat om totaal verschillende soorten systemen.

De waterpolitie en andere autoriteiten controleren schepen en vrachtschepen op naleving van de regels van het Inland ECDIS-systeem .
Het is belangrijk dat OpenCPN wordt weergegeven op de lijst van goedgekeurde software.

De Inland ECDIS standaard omvat ook het starten in de nachtmodus.
OpenCPN moet vooraf gedefinieerde schalen ingesteld hebben van de standaard radarbereiken.
Er zijn ook basis kaart weergave instellingen.

De Inland ECDIS Standard onderscheidt twee besturings instelligen: de Navigatiemodus en Informatiemodus OpenCPN houdt zich aan de informatiemodus.

De Inland ECDIS 2.4 vereist een handleiding in de talen EN, FR, NL, DE als een minimum eis.
====

== Correctie status van de handleiding

De bijlage bevat een bronlijst met de laatste wijzigingen op de pagina's van de handleiding.

== Bijlage

link:https://opencpn-manuals.github.io/inland-ecdis/manuals/en/sources.html[De laatste correcties]
