= Inland ECDIS Handbuch
:icons: font

== Einführung

Dieses Handbuch beschreibt die Verwendung von OpenCPN in der Version nach ECDIS Version 2.4 (Informationsmodus).

link:https://unece.org/fileadmin/DAM/trans/doc/2015/sc3wp3/Presentation_WP3_-_Inland_ECDIS_edition_2.4.pdf[Inland_ECDIS_edition_2.4]

Eine Einführung in Inland ECDIS finden Sie https://www.ccr-zkr.org/files/documents/workshops/wrshp181011/Leaflet_Inland_ECDIS_de.pdf[HIER].

Eine Seite mit nützlichen Links, einschließlich nationaler Organisationen, die sich mit IENCs befassen, gibt es https://ienc.openecdis.org/links[HIER].

Das Handbuch basiert auf Version 5.6.2 von OpenCPN. Es enthält keine Informationen über die Android-Version des Programms.

[NOTE]

====
Inland ECDIS ist ein Standard (aktuell 2.4) für Handelsschiffe auf Binnengewässern der EU.
Die entsprechenden S-57 Karten werden InlandENCs genannt und verfügen über einige spezifische Parameter.

Inland ECDIS darf nicht mit IMO ECDIS verwechselt werden.
Es handelt sich um zwei völlig unterschiedliche Systeme.

Die Wasserpolizei oder andere Behörden kontrollieren Schiffe auf die Einhaltung der Inland ECDIS-Vorschriften.
Deshalb ist es wichtig, dass OpenCPN als Standardkonforme Software gelistet ist.

Der Inland ECDIS Standard beinhaltet den Start im Nachtmodus.
Wie im Standard vorgegeben, zeigt OpenCPN vordefinierte Massstäbe, die aus den Standardradarbereichen abgeleitet sind.
Es gibt ebenfalls vordefinierte Kartendarstellungsmodi.

Der Inland ECDIS Standard unterscheidet zwei Betriebsmodi: Navigationsmodus und Informationsmodus. OpenCPN ist dem Informationsmodus konform.

Inland ECDIS 2.4 fordert die Verfügbarkeit von Handbüchern auf EN, FR, NL, DE .
====

== Korrekturstatus des Handbuchs

Der Anhang enthält eine Quellenliste, die die letzten Änderungen des Handbuchs zeigt.

== Annexe

link:https://opencpn-manuals.github.io/inland-ecdis/manuals/en/sources.html[Die letzten Änderungen]
