:experimental:

= OpenCPN installeren

Voor de eerste installatie is een internetverbinding nodig.
Met je internetbrowser ga je naar https://opencpn.org/OpenCPN/info/downloadopencpn.html[HERE] en ga naar de relevante sectie.

Als tijdens de installatie gevraagd wordt om een map te selecteren die de kaarten bevat. Deze stap van het proces overslaan. Kaarten worden gedekt door xref:charts.adoc[HERE].

== Windows

afbeelding:windows.png[Windows,]

Bestand downloaden Open het .exe en volg de instructies.

== Mac

afbeelding:apple.png[Apple,]

Download het .exe bestand. Open .pkg en volg de instructies in het installatieprogramma.

Omdat het programma niet uit de app store komt, moet je mogelijk toestemming geven om te installeren van een onbekende ontwikkelaar.

btn:[Systeemvoorkeuren] btn:[Veiligheid &amp; Privacy]

== Raspberry Pi

image:raspberry-pi.svg[Raspberry Pi,]

Je kunt OpenCPN installeren door een PPA (Pakketten Archief) van Ubuntu toe te voegen. Zie xref:configuring_ubuntu_ppa:configuring_ubuntu_ppa.adoc[Ubuntu PPA]

De eenvoudigste manier om OpenCPN op de Raspberry Pi te installeren is door https://openplotter.readthedocs.io/en/2.x.x/getting_started/installing.html[OpenPlotter] te gebruiken die OpenCPN en ook enkele plugins installeert.

== Ubuntu

image:ubuntu.svg[Ubuntu,]

Voor Ubuntu Linux en zijn afgeleiden (Linux Mint) en Debian Jessie gebaseerde distributies, wordt OpenCPN verspreid vanuit een PPA.
xref:configuring_ubuntu_ppa:configuring_ubuntu_ppa.adoc[Ubuntu PPA] legt uit hoe dit wordt gebruikt.

== Flatpak

afbeelding:flatpak.png[flatpak,]

OpenCPN Version 5.6.2 is available as a Flatpak package.  This packaging system is supported on all major Linux distributions.
https://flathub.org/apps/details/org.opencpn.OpenCPN[Simplified Installation Instructions]

--OR--

.Manual Installation:
. Install flatpak on your system as described in https://flatpak.org/setup/[flatpak.org/setup]
. Install OpenCPN Flatpak image using:

----
$ flatpak install --user  https://flathub.org/repo/appstream/org.opencpn.OpenCPN.flatpakref
----

Start OpenCPN:

----
$ flatpak run org.opencpn.OpenCPN
----

== Fedora

image:fedora.svg[Fedora,]

OpenCPN is not natively supported on Fedora.
Use the Flatpak release instead.

== Debian

image:debian.svg[Debian,]

For Debian derivatives, you can use the same packages as for the equivalent Ubuntu release.
For Debian Stable (Buster) you can use the packages from the https://launchpad.net/~opencpn/+archive/ubuntu/opencpn[Ubuntu PPA]. The compatible Ubuntu Release is Bionic (Ubuntu 18.04).

== Other OS

Refer to the https://opencpn.org/OpenCPN/info/downloadopencpn.html[Download page] for other Operating Systems.